table 'Amenity Table'
	lineageTag: d6d0253b-e9e8-421a-9dd7-8023659642d4

	column Amenity
		dataType: string
		lineageTag: 0a903e57-1c6f-44c2-a37a-114ce83ffab2
		summarizeBy: none
		sourceColumn: Amenity

		annotation SummarizationSetBy = Automatic

	column Sequence
		dataType: int64
		formatString: 0
		lineageTag: 204c12e5-285e-4127-8877-f68399885786
		summarizeBy: sum
		sourceColumn: Sequence

		annotation SummarizationSetBy = Automatic

	partition 'Amenity Table' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WckosTlUIKMpMTlXSUTJUitWJVgpILMrOzEsH8o3AfNec1LLEkvwioIAxWMC9MhfINoEozs/PAXJMIZyi1NzM0lyFkPySRJComVJsLAA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Amenity = _t, Sequence = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Amenity", type text}, {"Sequence", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

